name: K2P Build by Lean

on:
  push:
    tags:
      - '*'

env:
  SSH_ACTIONS: false
  REPO_URL: https://github.com/coolsnowwolf/lede.git
  REPO_BRANCH: master
  UPLOAD: true
  RELEASE: true
  WECHAT: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-18.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@main
      
      - name: Install depends
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /usr/lib/jvm /opt/ghc
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install $(curl -fsSL git.io/depends-ubuntu-1804)
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean
          sudo timedatectl set-timezone "$TZ"

      - name: Clone OpenWRT
        run: |
          cd ${{ github.workspace }}
          git clone --depth 1 $REPO_URL -b $REPO_BRANCH K2P
          useVersionInfo=$(git show -s --date=short --format="Author: %an<br/>Date: %cd<br/>Commit: %s")
          echo "::set-env name=useVersionInfo::$useVersionInfo"
          echo "::set-env name=DATE::$(TZ=UTC-8 date "+%Y%m%d")"
          echo "::set-env name=RELEASE_DATE::$(TZ=UTC-8 date "+%Y-%m-%d")"
      
      - name: Package source
        run: |
          cd ${{ github.workspace }}/K2P
          svn co https://github.com/rosywrt/luci-theme-rosy/trunk/luci-theme-rosy package/luci-theme-rosy

          ./scripts/feeds clean
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      
      - name: Build config
        run: |
          cd ${{ github.workspace }}
          [ -e shell/k2p.sh ] && mv shell/k2p.sh K2P/k2p.sh
          [ -e K2P/.config ] && rm -f K2P/.config
          cp config/k2p.conf K2P/.config
          cd ${{ github.workspace }}/K2P
          [ -e k2p.sh ] && chmod +x k2p.sh && bash k2p.sh
          make defconfig
      
      - name: SSH connection to Actions
        if: env.SSH_ACTIONS == 'true'
        uses: P3TERX/debugger-action@main
      
      - name: Download build dependencies
        run: |
          cd ${{ github.workspace }}/K2P
          make download -j8
      
      - name: Compile openwrt
        id: compile
        run: |
          cd ${{ github.workspace }}/K2P
          make -j$(nproc) V=s 2>&1 | tee build.log || make -j1 V=s 2>&1 | tee build.log
          ls -la ${{ github.workspace }}/K2P/bin/targets/*/*/
          echo ::set-env name=BUILD_STATUS::"success"
          echo ::set-env name=RELEASE_TAG::"$(TZ=UTC-8 date +"%Y.%m.%d")"
      
      - name: Copy file
        if: env.BUILD_STATUS == 'success' && !cancelled()
        run: |
          mkdir -p ${{ github.workspace }}/dist/packages
          cp -r -f ${{ github.workspace }}/K2P/bin/targets/ramips/mt7621/*.bin ${{ github.workspace }}/dist/
          cp -r -f ${{ github.workspace }}/K2P/bin/targets/ramips/mt7621/*.buildinfo ${{ github.workspace }}/dist/
          cp -r -f ${{ github.workspace }}/K2P/bin/targets/ramips/mt7621/*.manifest ${{ github.workspace }}/dist/

          cp -r -f ${{ github.workspace }}/K2P/bin/packages/mipsel_24kc/*/*.ipk ${{ github.workspace }}/dist/packages/
          cp -r -f ${{ github.workspace }}/K2P/bin/targets/ramips/mt7621/packages/*.ipk ${{ github.workspace }}/dist/packages/

          cd ${{ github.workspace }}/dist
          tar -czf packages.tar.gz packages
          rm -rf packages
          sha256sum `ls -1 | sort` > sha256sums

          tar -czf K2P.tar.gz *
      
      - name: Upload release
        if: env.BUILD_STATUS == 'success' && env.RELEASE == 'true' && !cancelled()
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          body_path: ${{ github.workspace }}/CHANGELOG.md
          files: ${{ github.workspace }}/dist/K2P.tar.gz

      - name: WeChat
        if: env.BUILD_STATUS == 'success' && env.WECHAT == 'true' && !cancelled()
        uses: emon100/Action-Serverchan@master
        with:
          SCKEY: ${{ secrets.SCKEY }}
          text: K2P固件编译完成！
          desp: 编译日期：${{ env.RELEASE_TAG }}